CREATE SCHEMA "production";
--> statement-breakpoint
CREATE TABLE "production"."application" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."application_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"job_id" integer NOT NULL,
	"status" text DEFAULT 'backlog' NOT NULL,
	"channel" text,
	"applied_at" text,
	"candidate_document_id" integer,
	"cover_letter_path" text,
	"contact_name" text,
	"contact_url" text,
	"rate_discussed" text,
	"next_action" text,
	"next_action_at" text,
	"notes" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."application_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."application_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"application_id" integer NOT NULL,
	"at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"kind" text NOT NULL,
	"from_status" text,
	"to_status" text,
	"detail" text
);
--> statement-breakpoint
CREATE TABLE "production"."auth_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."auth_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"email" text,
	"kind" text NOT NULL,
	"detail" text,
	"at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."auth_login_token" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."auth_login_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"email" text NOT NULL,
	"purpose" text DEFAULT 'login' NOT NULL,
	"expires_at" text NOT NULL,
	"used_at" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."auth_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."auth_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"user_id" integer NOT NULL,
	"expires_at" text NOT NULL,
	"impersonated_by" integer,
	"revoked_at" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."auth_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."auth_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"full_name" text,
	"roles" json NOT NULL,
	"password_hash" text,
	"candidate_id" integer,
	"disabled_at" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."candidate" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."candidate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"headline" text,
	"location" text,
	"email" text,
	"linkedin_url" text,
	"github_url" text,
	"is_default" boolean DEFAULT false NOT NULL,
	"visibility" text DEFAULT 'private' NOT NULL,
	"public_cv" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."candidate_document" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."candidate_document_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"kind" text DEFAULT 'cv' NOT NULL,
	"label" text NOT NULL,
	"format" text DEFAULT 'text' NOT NULL,
	"content" text NOT NULL,
	"source_filename" text,
	"is_current" boolean DEFAULT true NOT NULL,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	CONSTRAINT "candidate_document_identity_idx" UNIQUE("id","candidate_id")
);
--> statement-breakpoint
CREATE TABLE "production"."candidate_matching_profile" (
	"candidate_id" integer PRIMARY KEY NOT NULL,
	"profile_json" text NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."candidate_skill" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."candidate_skill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"skill_id" integer NOT NULL,
	"source" text DEFAULT 'cv' NOT NULL,
	"status" text DEFAULT 'detected' NOT NULL,
	"evidence" text,
	"level" text,
	"occurrences" integer DEFAULT 1 NOT NULL,
	"detected_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"audited_at" text,
	"audited_by" text
);
--> statement-breakpoint
CREATE TABLE "production"."company" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"website" text,
	"careers_url" text,
	"hires_contractors" boolean,
	"hires_latam" boolean,
	"via_agency" text,
	"notes" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."engagement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."engagement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"target_url" text NOT NULL,
	"target_name" text,
	"target_role" text,
	"target_company" text,
	"rationale" text,
	"draft" text,
	"status" text DEFAULT 'queued' NOT NULL,
	"queued_for" text,
	"done_at" text,
	"outcome" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."fx_rate" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."fx_rate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" text NOT NULL,
	"base" text NOT NULL,
	"currency" text NOT NULL,
	"rate" double precision NOT NULL,
	"provider" text NOT NULL,
	"fetched_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."job" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."job_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fingerprint" text NOT NULL,
	"content_hash" text NOT NULL,
	"source_id" text NOT NULL,
	"external_id" text NOT NULL,
	"company_id" integer,
	"company_name" text NOT NULL,
	"title" text NOT NULL,
	"description_html" text,
	"description_text" text,
	"posted_by_user_id" integer,
	"checked_at" text,
	"check_status" text,
	"check_code" integer,
	"location_raw" text,
	"remote" boolean,
	"employment_type" text,
	"seniority_raw" text,
	"comp_min" integer,
	"comp_max" integer,
	"comp_currency" text,
	"comp_period" text,
	"url" text NOT NULL,
	"apply_url" text,
	"posted_at" text,
	"first_seen_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"last_seen_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"closed_at" text,
	"raw" json NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."job_page" (
	"job_id" integer PRIMARY KEY NOT NULL,
	"final_url" text NOT NULL,
	"http_status" integer NOT NULL,
	"html" text,
	"text" text,
	"extracted" json,
	"content_hash" text NOT NULL,
	"bytes" integer DEFAULT 0 NOT NULL,
	"fetched_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"parsed_at" text
);
--> statement-breakpoint
CREATE TABLE "production"."job_score" (
	"candidate_id" integer NOT NULL,
	"job_id" integer NOT NULL,
	"fit" double precision NOT NULL,
	"title_score" double precision NOT NULL,
	"keyword_score" double precision NOT NULL,
	"seniority_score" double precision NOT NULL,
	"geo_score" double precision NOT NULL,
	"comp_score" double precision NOT NULL,
	"freshness_score" double precision DEFAULT 0 NOT NULL,
	"benefit_score" double precision DEFAULT 0 NOT NULL,
	"penalty" double precision DEFAULT 0 NOT NULL,
	"cluster" text NOT NULL,
	"matched_keywords" json NOT NULL,
	"missing_keywords" json NOT NULL,
	"detected_benefits" json,
	"age_days" integer,
	"reasons" json NOT NULL,
	"blockers" json NOT NULL,
	"eligibility_status" text DEFAULT 'unverifiable' NOT NULL,
	"eligibility_reasons" json DEFAULT '[]' NOT NULL,
	"scorer_version" text NOT NULL,
	"profile_hash" text DEFAULT 'legacy' NOT NULL,
	"scored_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	CONSTRAINT "job_score_candidate_job_pk" PRIMARY KEY("candidate_id","job_id")
);
--> statement-breakpoint
CREATE TABLE "production"."llm_model" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."llm_model_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider_id" integer NOT NULL,
	"model_id" text NOT NULL,
	"label" text NOT NULL,
	"supports_reasoning" boolean DEFAULT false NOT NULL,
	"default_effort" text,
	"max_output_tokens" integer DEFAULT 4096 NOT NULL,
	"input_cost_per_mtok" double precision,
	"output_cost_per_mtok" double precision,
	"enabled" boolean DEFAULT true NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."llm_provider" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."llm_provider_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"label" text NOT NULL,
	"kind" text NOT NULL,
	"base_url" text,
	"api_key_env" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"notes" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."mail_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."mail_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"message_id" text NOT NULL,
	"from_address" text,
	"from_name" text,
	"subject" text,
	"received_at" text,
	"kind" text DEFAULT 'unknown' NOT NULL,
	"provider" text,
	"company_guess" text,
	"body_text" text,
	"extracted_jobs" integer DEFAULT 0 NOT NULL,
	"imported_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."mail_suggestion" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."mail_suggestion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mail_id" integer NOT NULL,
	"application_id" integer,
	"job_id" integer,
	"suggested_status" text,
	"rationale" text,
	"confidence" double precision DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"decided_at" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."metric_snapshot" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."metric_snapshot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"at" text NOT NULL,
	"key" text NOT NULL,
	"value" double precision NOT NULL,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "production"."positioning_task" (
	"id" text PRIMARY KEY NOT NULL,
	"horizon" text NOT NULL,
	"title" text NOT NULL,
	"why" text,
	"how" text,
	"expected" text,
	"priority" text NOT NULL,
	"effort" text,
	"status" text DEFAULT 'todo' NOT NULL,
	"done_at" text,
	"source_ref" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"pillar" text NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"lang" text DEFAULT 'en' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"scheduled_for" text,
	"published_at" text,
	"linkedin_urn" text,
	"impressions" integer,
	"reactions" integer,
	"comment_count" integer,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."recruiter_candidate" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."recruiter_candidate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recruiter_user_id" integer NOT NULL,
	"candidate_id" integer NOT NULL,
	"created_by" integer,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."score_task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."score_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"origin" text DEFAULT 'cv' NOT NULL,
	"priority" double precision DEFAULT 0 NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"scored" integer,
	"claimed_at" text,
	"claimed_by" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."scrape_task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."scrape_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_id" integer NOT NULL,
	"url" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"priority" double precision DEFAULT 0 NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"claimed_at" text,
	"claimed_by" text,
	"run_after" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."skill" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."skill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"canonical_name" text NOT NULL,
	"category" text NOT NULL,
	"aliases" json NOT NULL,
	"verified_at" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."source" (
	"id" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"handle" text NOT NULL,
	"label" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"rationale" text,
	"last_synced_at" text,
	"last_status" text,
	"last_error" text,
	"last_job_count" integer,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."target_account" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."target_account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"linkedin_url" text,
	"category" text NOT NULL,
	"company" text,
	"role" text,
	"country" text,
	"status" text DEFAULT 'identified' NOT NULL,
	"last_touch_at" text,
	"notes" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."verify_task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."verify_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_id" integer NOT NULL,
	"url" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"priority" double precision DEFAULT 0 NOT NULL,
	"origin" text DEFAULT 'periodic' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"claimed_at" text,
	"claimed_by" text,
	"run_after" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
ALTER TABLE "production"."application" ADD CONSTRAINT "application_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."application" ADD CONSTRAINT "application_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."application" ADD CONSTRAINT "application_candidate_document_fk" FOREIGN KEY ("candidate_document_id","candidate_id") REFERENCES "production"."candidate_document"("id","candidate_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."application_event" ADD CONSTRAINT "application_event_application_id_application_id_fk" FOREIGN KEY ("application_id") REFERENCES "production"."application"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."auth_event" ADD CONSTRAINT "auth_event_user_id_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."auth_session" ADD CONSTRAINT "auth_session_user_id_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "production"."auth_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."auth_session" ADD CONSTRAINT "auth_session_impersonated_by_auth_user_id_fk" FOREIGN KEY ("impersonated_by") REFERENCES "production"."auth_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."auth_user" ADD CONSTRAINT "auth_user_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."candidate_document" ADD CONSTRAINT "candidate_document_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."candidate_matching_profile" ADD CONSTRAINT "candidate_matching_profile_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."candidate_skill" ADD CONSTRAINT "candidate_skill_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."candidate_skill" ADD CONSTRAINT "candidate_skill_skill_id_skill_id_fk" FOREIGN KEY ("skill_id") REFERENCES "production"."skill"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."job" ADD CONSTRAINT "job_source_id_source_id_fk" FOREIGN KEY ("source_id") REFERENCES "production"."source"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."job" ADD CONSTRAINT "job_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "production"."company"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."job" ADD CONSTRAINT "job_posted_by_user_id_auth_user_id_fk" FOREIGN KEY ("posted_by_user_id") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."job_page" ADD CONSTRAINT "job_page_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."job_score" ADD CONSTRAINT "job_score_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."job_score" ADD CONSTRAINT "job_score_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."llm_model" ADD CONSTRAINT "llm_model_provider_id_llm_provider_id_fk" FOREIGN KEY ("provider_id") REFERENCES "production"."llm_provider"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."mail_suggestion" ADD CONSTRAINT "mail_suggestion_mail_id_mail_message_id_fk" FOREIGN KEY ("mail_id") REFERENCES "production"."mail_message"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."mail_suggestion" ADD CONSTRAINT "mail_suggestion_application_id_application_id_fk" FOREIGN KEY ("application_id") REFERENCES "production"."application"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."mail_suggestion" ADD CONSTRAINT "mail_suggestion_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_candidate" ADD CONSTRAINT "recruiter_candidate_recruiter_user_id_auth_user_id_fk" FOREIGN KEY ("recruiter_user_id") REFERENCES "production"."auth_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_candidate" ADD CONSTRAINT "recruiter_candidate_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_candidate" ADD CONSTRAINT "recruiter_candidate_created_by_auth_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."score_task" ADD CONSTRAINT "score_task_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."scrape_task" ADD CONSTRAINT "scrape_task_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."verify_task" ADD CONSTRAINT "verify_task_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "application_candidate_job_idx" ON "production"."application" USING btree ("candidate_id","job_id");--> statement-breakpoint
CREATE INDEX "application_candidate_idx" ON "production"."application" USING btree ("candidate_id");--> statement-breakpoint
CREATE INDEX "application_candidate_document_idx" ON "production"."application" USING btree ("candidate_document_id");--> statement-breakpoint
CREATE INDEX "application_status_idx" ON "production"."application" USING btree ("status");--> statement-breakpoint
CREATE INDEX "application_next_action_idx" ON "production"."application" USING btree ("next_action_at");--> statement-breakpoint
CREATE INDEX "application_event_app_idx" ON "production"."application_event" USING btree ("application_id");--> statement-breakpoint
CREATE INDEX "auth_event_at_idx" ON "production"."auth_event" USING btree ("at");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_login_token_idx" ON "production"."auth_login_token" USING btree ("token_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_session_token_idx" ON "production"."auth_session" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "auth_session_user_idx" ON "production"."auth_session" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_user_email_idx" ON "production"."auth_user" USING btree ("email");--> statement-breakpoint
CREATE UNIQUE INDEX "candidate_slug_idx" ON "production"."candidate" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "candidate_document_candidate_idx" ON "production"."candidate_document" USING btree ("candidate_id","kind");--> statement-breakpoint
CREATE UNIQUE INDEX "candidate_document_one_current_idx" ON "production"."candidate_document" USING btree ("candidate_id","kind") WHERE "production"."candidate_document"."is_current" = true;--> statement-breakpoint
CREATE UNIQUE INDEX "candidate_skill_unique_idx" ON "production"."candidate_skill" USING btree ("candidate_id","skill_id");--> statement-breakpoint
CREATE INDEX "candidate_skill_status_idx" ON "production"."candidate_skill" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "company_slug_idx" ON "production"."company" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "engagement_status_idx" ON "production"."engagement" USING btree ("status","queued_for");--> statement-breakpoint
CREATE UNIQUE INDEX "fx_rate_unique_idx" ON "production"."fx_rate" USING btree ("date","base","currency");--> statement-breakpoint
CREATE UNIQUE INDEX "job_fingerprint_idx" ON "production"."job" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "job_source_idx" ON "production"."job" USING btree ("source_id");--> statement-breakpoint
CREATE INDEX "job_company_idx" ON "production"."job" USING btree ("company_name");--> statement-breakpoint
CREATE INDEX "job_last_seen_idx" ON "production"."job" USING btree ("last_seen_at");--> statement-breakpoint
CREATE INDEX "job_closed_idx" ON "production"."job" USING btree ("closed_at");--> statement-breakpoint
CREATE INDEX "job_page_parsed_idx" ON "production"."job_page" USING btree ("parsed_at");--> statement-breakpoint
CREATE INDEX "job_score_fit_idx" ON "production"."job_score" USING btree ("fit");--> statement-breakpoint
CREATE INDEX "job_score_candidate_idx" ON "production"."job_score" USING btree ("candidate_id");--> statement-breakpoint
CREATE UNIQUE INDEX "llm_model_unique_idx" ON "production"."llm_model" USING btree ("provider_id","model_id");--> statement-breakpoint
CREATE INDEX "llm_model_default_idx" ON "production"."llm_model" USING btree ("is_default");--> statement-breakpoint
CREATE UNIQUE INDEX "llm_provider_slug_idx" ON "production"."llm_provider" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "mail_message_id_idx" ON "production"."mail_message" USING btree ("message_id");--> statement-breakpoint
CREATE INDEX "mail_kind_idx" ON "production"."mail_message" USING btree ("kind");--> statement-breakpoint
CREATE INDEX "mail_received_idx" ON "production"."mail_message" USING btree ("received_at");--> statement-breakpoint
CREATE INDEX "mail_suggestion_status_idx" ON "production"."mail_suggestion" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "metric_at_key_idx" ON "production"."metric_snapshot" USING btree ("at","key");--> statement-breakpoint
CREATE UNIQUE INDEX "post_slug_idx" ON "production"."post" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "recruiter_candidate_idx" ON "production"."recruiter_candidate" USING btree ("recruiter_user_id","candidate_id");--> statement-breakpoint
CREATE INDEX "recruiter_candidate_candidate_idx" ON "production"."recruiter_candidate" USING btree ("candidate_id");--> statement-breakpoint
CREATE UNIQUE INDEX "score_task_candidate_idx" ON "production"."score_task" USING btree ("candidate_id");--> statement-breakpoint
CREATE INDEX "score_task_claim_idx" ON "production"."score_task" USING btree ("status","priority");--> statement-breakpoint
CREATE UNIQUE INDEX "scrape_task_job_idx" ON "production"."scrape_task" USING btree ("job_id");--> statement-breakpoint
CREATE INDEX "scrape_task_claim_idx" ON "production"."scrape_task" USING btree ("status","priority");--> statement-breakpoint
CREATE UNIQUE INDEX "skill_slug_idx" ON "production"."skill" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "skill_category_idx" ON "production"."skill" USING btree ("category");--> statement-breakpoint
CREATE UNIQUE INDEX "source_kind_handle_idx" ON "production"."source" USING btree ("kind","handle");--> statement-breakpoint
CREATE UNIQUE INDEX "target_account_url_idx" ON "production"."target_account" USING btree ("linkedin_url");--> statement-breakpoint
CREATE UNIQUE INDEX "verify_task_job_idx" ON "production"."verify_task" USING btree ("job_id");--> statement-breakpoint
CREATE INDEX "verify_task_claim_idx" ON "production"."verify_task" USING btree ("status","priority");