CREATE TABLE "production"."saved_term" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."saved_term_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"track_id" integer NOT NULL,
	"term" text NOT NULL,
	"term_key" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"paused_reason" text,
	"last_run_requested_at" text,
	"last_visit_at" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."target_track" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."target_track_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"name" text NOT NULL,
	"name_key" text NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"position" integer NOT NULL,
	"target_json" text,
	"unreviewed_json" text DEFAULT '[]' NOT NULL,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
ALTER TABLE "production"."job_score" ADD COLUMN "track_id" integer;--> statement-breakpoint
ALTER TABLE "production"."saved_term" ADD CONSTRAINT "saved_term_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."saved_term" ADD CONSTRAINT "saved_term_track_id_target_track_id_fk" FOREIGN KEY ("track_id") REFERENCES "production"."target_track"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."target_track" ADD CONSTRAINT "target_track_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "saved_term_candidate_key_idx" ON "production"."saved_term" USING btree ("candidate_id","term_key");--> statement-breakpoint
CREATE INDEX "saved_term_key_status_idx" ON "production"."saved_term" USING btree ("term_key","status");--> statement-breakpoint
CREATE UNIQUE INDEX "target_track_name_idx" ON "production"."target_track" USING btree ("candidate_id","name_key");--> statement-breakpoint
CREATE UNIQUE INDEX "target_track_one_primary_idx" ON "production"."target_track" USING btree ("candidate_id") WHERE "production"."target_track"."is_primary" = true;--> statement-breakpoint
ALTER TABLE "production"."job_score" ADD CONSTRAINT "job_score_track_id_target_track_id_fk" FOREIGN KEY ("track_id") REFERENCES "production"."target_track"("id") ON DELETE cascade ON UPDATE no action;