CREATE TABLE "production"."platform_quota" (
	"platform" text NOT NULL,
	"window_kind" text NOT NULL,
	"window_start" text NOT NULL,
	"used" integer NOT NULL,
	CONSTRAINT "platform_quota_pk" PRIMARY KEY("platform","window_kind","window_start")
);
--> statement-breakpoint
CREATE TABLE "production"."term_attribution" (
	"term_key" text NOT NULL,
	"job_id" integer NOT NULL,
	"platform" text NOT NULL,
	"attributed_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	CONSTRAINT "term_attribution_pk" PRIMARY KEY("term_key","job_id")
);
--> statement-breakpoint
CREATE TABLE "production"."term_capture" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."term_capture_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"platform" text NOT NULL,
	"term_key" text NOT NULL,
	"query" text NOT NULL,
	"window_day" text NOT NULL,
	"origin" text NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"reason_code" text,
	"priority" double precision DEFAULT 0 NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"run_after" text,
	"claimed_at" text,
	"claimed_by" text,
	"fetched" integer DEFAULT 0 NOT NULL,
	"created" integer DEFAULT 0 NOT NULL,
	"known" integer DEFAULT 0 NOT NULL,
	"attributed" integer DEFAULT 0 NOT NULL,
	"total_hint" integer,
	"started_at" text,
	"finished_at" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"updated_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
ALTER TABLE "production"."term_attribution" ADD CONSTRAINT "term_attribution_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "term_attribution_job_idx" ON "production"."term_attribution" USING btree ("job_id");--> statement-breakpoint
CREATE UNIQUE INDEX "term_capture_window_idx" ON "production"."term_capture" USING btree ("platform","term_key","window_day");--> statement-breakpoint
CREATE INDEX "term_capture_claim_idx" ON "production"."term_capture" USING btree ("status","priority");