CREATE TABLE "production"."sweep_lease" (
	"key" text PRIMARY KEY NOT NULL,
	"claimed_at" text,
	"claimed_by" text,
	"last_claimed_at" text,
	"last_finished_at" text
);
--> statement-breakpoint
CREATE TABLE "production"."sweep_run" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."sweep_run_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slice" text NOT NULL,
	"unit" text,
	"started_at" text NOT NULL,
	"duration_ms" integer NOT NULL,
	"items" integer DEFAULT 0 NOT NULL,
	"errors" integer DEFAULT 0 NOT NULL,
	"error" text
);
--> statement-breakpoint
CREATE INDEX "sweep_run_slice_started_idx" ON "production"."sweep_run" USING btree ("slice","started_at");