CREATE TABLE "production"."job_analysis" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."job_analysis_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_id" integer NOT NULL,
	"requested_by" integer,
	"retry_of" integer,
	"status" text DEFAULT 'queued' NOT NULL,
	"input_hash" text NOT NULL,
	"prompt_version" text NOT NULL,
	"schema_version" text NOT NULL,
	"provider_slug" text,
	"model_id" text,
	"result" json,
	"error_code" text,
	"input_tokens" integer,
	"output_tokens" integer,
	"cost_estimate" double precision,
	"claimed_at" text,
	"heartbeat_at" text,
	"finished_at" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
ALTER TABLE "production"."job_analysis" ADD CONSTRAINT "job_analysis_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."job_analysis" ADD CONSTRAINT "job_analysis_requested_by_auth_user_id_fk" FOREIGN KEY ("requested_by") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."job_analysis" ADD CONSTRAINT "job_analysis_retry_of_fk" FOREIGN KEY ("retry_of") REFERENCES "production"."job_analysis"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "job_analysis_active_idx" ON "production"."job_analysis" USING btree ("job_id","input_hash","schema_version") WHERE "production"."job_analysis"."status" in ('queued', 'running');--> statement-breakpoint
CREATE INDEX "job_analysis_job_idx" ON "production"."job_analysis" USING btree ("job_id","id");--> statement-breakpoint
CREATE INDEX "job_analysis_claim_idx" ON "production"."job_analysis" USING btree ("status","id");