CREATE TABLE "production"."job_check_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."job_check_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_id" integer NOT NULL,
	"run_id" integer,
	"checked_at" text NOT NULL,
	"verdict" text NOT NULL,
	"http_code" integer,
	"reason" text NOT NULL,
	"evidence" text
);
--> statement-breakpoint
ALTER TABLE "production"."job_check_event" ADD CONSTRAINT "job_check_event_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."job_check_event" ADD CONSTRAINT "job_check_event_run_id_source_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "production"."source_run"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "job_check_event_job_idx" ON "production"."job_check_event" USING btree ("job_id","checked_at");