CREATE TABLE "production"."source_run" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."source_run_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scope_kind" text NOT NULL,
	"source_id" text,
	"parent_id" integer,
	"retry_of" integer,
	"idempotency_key" text NOT NULL,
	"actor_user_id" integer,
	"config_snapshot" jsonb NOT NULL,
	"status" text NOT NULL,
	"heartbeat_at" text,
	"queued_at" text NOT NULL,
	"started_at" text,
	"finished_at" text,
	"fetched" integer,
	"inserted" integer,
	"updated" integer,
	"unchanged" integer,
	"closed" integer,
	"alive" integer,
	"inconclusive" integer,
	"completeness" text,
	"error_code" text,
	"error_detail" text
);
--> statement-breakpoint
ALTER TABLE "production"."source_run" ADD CONSTRAINT "source_run_source_id_source_id_fk" FOREIGN KEY ("source_id") REFERENCES "production"."source"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."source_run" ADD CONSTRAINT "source_run_parent_id_source_run_id_fk" FOREIGN KEY ("parent_id") REFERENCES "production"."source_run"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."source_run" ADD CONSTRAINT "source_run_retry_of_source_run_id_fk" FOREIGN KEY ("retry_of") REFERENCES "production"."source_run"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."source_run" ADD CONSTRAINT "source_run_actor_user_id_auth_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "source_run_active_key_idx" ON "production"."source_run" USING btree ("idempotency_key") WHERE "production"."source_run"."status" in ('queued', 'running');--> statement-breakpoint
CREATE INDEX "source_run_queued_idx" ON "production"."source_run" USING btree ("queued_at");--> statement-breakpoint
CREATE INDEX "source_run_parent_idx" ON "production"."source_run" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "source_run_source_idx" ON "production"."source_run" USING btree ("source_id");