CREATE TABLE "production"."quota_watch" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."quota_watch_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"checked_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"vercel_deploys_24h" integer,
	"actions_queue_max_wait_s" integer,
	"actions_status" text,
	"decision" text NOT NULL,
	"trigger" text,
	"action_recommended" text,
	"reversal_command" text,
	"note" text,
	"issue_number" integer
);
--> statement-breakpoint
CREATE INDEX "quota_watch_checked_at_idx" ON "production"."quota_watch" USING btree ("checked_at");