CREATE TABLE "production"."auth_identity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."auth_identity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"provider" text NOT NULL,
	"subject" text NOT NULL,
	"email_at_link" text,
	"origin" text NOT NULL,
	"linked_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"last_used_at" text,
	CONSTRAINT "auth_identity_provider_check" CHECK ("production"."auth_identity"."provider" in ('google', 'linkedin')),
	CONSTRAINT "auth_identity_origin_check" CHECK ("production"."auth_identity"."origin" in ('automatic', 'manual'))
);
--> statement-breakpoint
CREATE TABLE "production"."auth_signup" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."auth_signup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"token_hash" text NOT NULL,
	"email" text NOT NULL,
	"locale" text NOT NULL,
	"role" text,
	"name" text,
	"headline" text,
	"cv_text" text,
	"password_hash" text,
	"provider" text,
	"subject" text,
	"code_hash" text,
	"code_attempts" integer DEFAULT 0 NOT NULL,
	"code_sent_at" text,
	"ip_hmac" text NOT NULL,
	"terms_version" text,
	"privacy_version" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"expires_at" text NOT NULL,
	"completed_at" text,
	"user_id" integer,
	CONSTRAINT "auth_signup_kind_check" CHECK ("production"."auth_signup"."kind" in ('manual', 'social')),
	CONSTRAINT "auth_signup_role_check" CHECK ("production"."auth_signup"."role" is null or "production"."auth_signup"."role" in ('candidate', 'recruiter')),
	CONSTRAINT "auth_signup_provider_check" CHECK ("production"."auth_signup"."provider" is null or "production"."auth_signup"."provider" in ('google', 'linkedin'))
);
--> statement-breakpoint
ALTER TABLE "production"."auth_user" ADD COLUMN "email_verified_at" text;--> statement-breakpoint
ALTER TABLE "production"."auth_user" ADD COLUMN "terms_version" text;--> statement-breakpoint
ALTER TABLE "production"."auth_user" ADD COLUMN "privacy_version" text;--> statement-breakpoint
ALTER TABLE "production"."auth_user" ADD COLUMN "terms_accepted_at" text;--> statement-breakpoint
ALTER TABLE "production"."auth_user" ADD COLUMN "signup_origin" text;--> statement-breakpoint
ALTER TABLE "production"."auth_user" ADD COLUMN "locale" text;--> statement-breakpoint
ALTER TABLE "production"."auth_identity" ADD CONSTRAINT "auth_identity_user_id_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "production"."auth_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."auth_signup" ADD CONSTRAINT "auth_signup_user_id_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "auth_identity_subject_idx" ON "production"."auth_identity" USING btree ("provider","subject");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_identity_user_provider_idx" ON "production"."auth_identity" USING btree ("user_id","provider");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_signup_token_idx" ON "production"."auth_signup" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "auth_signup_ip_idx" ON "production"."auth_signup" USING btree ("ip_hmac","completed_at");--> statement-breakpoint
CREATE INDEX "auth_signup_email_idx" ON "production"."auth_signup" USING btree ("email","completed_at");