CREATE TABLE "production"."recruiter_access_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."recruiter_access_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"grant_id" integer,
	"invite_id" integer,
	"suggestion_id" integer,
	"recruiter_email" text NOT NULL,
	"kind" text NOT NULL,
	"actor" text NOT NULL,
	"actor_user_id" integer,
	"actor_name" text,
	"detail" text,
	"at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	CONSTRAINT "recruiter_access_event_kind_check" CHECK ("production"."recruiter_access_event"."kind" in ('invite_sent', 'invite_resent', 'invite_cancelled', 'invite_expired', 'invite_accepted', 'grant_created', 'end_date_changed', 'access_revoked', 'access_expired', 'access_ended_account_removed', 'suggestion_received', 'suggestion_accepted', 'suggestion_declined')),
	CONSTRAINT "recruiter_access_event_actor_check" CHECK ("production"."recruiter_access_event"."actor" in ('candidate', 'admin', 'recruiter', 'system'))
);
--> statement-breakpoint
CREATE TABLE "production"."recruiter_directory_query" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."recruiter_directory_query_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recruiter_user_id" integer NOT NULL,
	"at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production"."recruiter_grant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."recruiter_grant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"recruiter_user_id" integer,
	"recruiter_email" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"invite_id" integer,
	"created_by" integer,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"expires_at" text,
	"expiry_tz" text,
	"ended_at" text,
	"revoked_by" integer,
	"last_accessed_at" text,
	CONSTRAINT "recruiter_grant_status_check" CHECK ("production"."recruiter_grant"."status" in ('active', 'revoked', 'expired', 'ended_account_removed')),
	CONSTRAINT "recruiter_grant_active_recruiter_check" CHECK ("production"."recruiter_grant"."status" <> 'active' or "production"."recruiter_grant"."recruiter_user_id" is not null)
);
--> statement-breakpoint
CREATE TABLE "production"."recruiter_invite" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."recruiter_invite_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"email" text NOT NULL,
	"token_hash" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"expires_at" text NOT NULL,
	"access_expires_at" text,
	"expiry_tz" text,
	"created_by" integer,
	"cancelled_by" integer,
	"accepted_user_id" integer,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"decided_at" text,
	"delivery_failed_at" text,
	"dismissed_at" text,
	CONSTRAINT "recruiter_invite_status_check" CHECK ("production"."recruiter_invite"."status" in ('pending', 'accepted', 'expired', 'cancelled', 'superseded'))
);
--> statement-breakpoint
CREATE TABLE "production"."recruiter_suggestion" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."recruiter_suggestion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_id" integer NOT NULL,
	"job_id" integer NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"application_id" integer,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"decided_at" text,
	CONSTRAINT "recruiter_suggestion_status_check" CHECK ("production"."recruiter_suggestion"."status" in ('pending', 'accepted', 'declined'))
);
--> statement-breakpoint
CREATE TABLE "production"."recruiter_suggestion_by" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "production"."recruiter_suggestion_by_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"suggestion_id" integer NOT NULL,
	"recruiter_user_id" integer,
	"recruiter_email" text NOT NULL,
	"grant_id" integer,
	"note" text,
	"created_at" text DEFAULT to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') NOT NULL,
	"notified_at" text,
	CONSTRAINT "recruiter_suggestion_by_note_check" CHECK (char_length("production"."recruiter_suggestion_by"."note") <= 500)
);
--> statement-breakpoint
ALTER TABLE "production"."recruiter_access_event" ADD CONSTRAINT "recruiter_access_event_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_access_event" ADD CONSTRAINT "recruiter_access_event_grant_id_recruiter_grant_id_fk" FOREIGN KEY ("grant_id") REFERENCES "production"."recruiter_grant"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_access_event" ADD CONSTRAINT "recruiter_access_event_invite_id_recruiter_invite_id_fk" FOREIGN KEY ("invite_id") REFERENCES "production"."recruiter_invite"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_access_event" ADD CONSTRAINT "recruiter_access_event_suggestion_id_recruiter_suggestion_id_fk" FOREIGN KEY ("suggestion_id") REFERENCES "production"."recruiter_suggestion"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_access_event" ADD CONSTRAINT "recruiter_access_event_actor_user_id_auth_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_directory_query" ADD CONSTRAINT "recruiter_directory_query_recruiter_user_id_auth_user_id_fk" FOREIGN KEY ("recruiter_user_id") REFERENCES "production"."auth_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_grant" ADD CONSTRAINT "recruiter_grant_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_grant" ADD CONSTRAINT "recruiter_grant_recruiter_user_id_auth_user_id_fk" FOREIGN KEY ("recruiter_user_id") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_grant" ADD CONSTRAINT "recruiter_grant_invite_id_recruiter_invite_id_fk" FOREIGN KEY ("invite_id") REFERENCES "production"."recruiter_invite"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_grant" ADD CONSTRAINT "recruiter_grant_created_by_auth_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_grant" ADD CONSTRAINT "recruiter_grant_revoked_by_auth_user_id_fk" FOREIGN KEY ("revoked_by") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_invite" ADD CONSTRAINT "recruiter_invite_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_invite" ADD CONSTRAINT "recruiter_invite_created_by_auth_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_invite" ADD CONSTRAINT "recruiter_invite_cancelled_by_auth_user_id_fk" FOREIGN KEY ("cancelled_by") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_invite" ADD CONSTRAINT "recruiter_invite_accepted_user_id_auth_user_id_fk" FOREIGN KEY ("accepted_user_id") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_suggestion" ADD CONSTRAINT "recruiter_suggestion_candidate_id_candidate_id_fk" FOREIGN KEY ("candidate_id") REFERENCES "production"."candidate"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_suggestion" ADD CONSTRAINT "recruiter_suggestion_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "production"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_suggestion" ADD CONSTRAINT "recruiter_suggestion_application_id_application_id_fk" FOREIGN KEY ("application_id") REFERENCES "production"."application"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_suggestion_by" ADD CONSTRAINT "recruiter_suggestion_by_recruiter_user_id_auth_user_id_fk" FOREIGN KEY ("recruiter_user_id") REFERENCES "production"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_suggestion_by" ADD CONSTRAINT "recruiter_suggestion_by_grant_id_recruiter_grant_id_fk" FOREIGN KEY ("grant_id") REFERENCES "production"."recruiter_grant"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production"."recruiter_suggestion_by" ADD CONSTRAINT "recruiter_suggestion_by_suggestion_fk" FOREIGN KEY ("suggestion_id") REFERENCES "production"."recruiter_suggestion"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "recruiter_access_event_candidate_idx" ON "production"."recruiter_access_event" USING btree ("candidate_id","at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "recruiter_directory_query_idx" ON "production"."recruiter_directory_query" USING btree ("recruiter_user_id","at");--> statement-breakpoint
CREATE UNIQUE INDEX "recruiter_grant_active_idx" ON "production"."recruiter_grant" USING btree ("candidate_id","recruiter_user_id") WHERE "production"."recruiter_grant"."status" = 'active';--> statement-breakpoint
CREATE INDEX "recruiter_grant_recruiter_idx" ON "production"."recruiter_grant" USING btree ("recruiter_user_id","status");--> statement-breakpoint
CREATE INDEX "recruiter_grant_candidate_idx" ON "production"."recruiter_grant" USING btree ("candidate_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "recruiter_invite_token_idx" ON "production"."recruiter_invite" USING btree ("token_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "recruiter_invite_pending_idx" ON "production"."recruiter_invite" USING btree ("candidate_id","email") WHERE "production"."recruiter_invite"."status" = 'pending';--> statement-breakpoint
CREATE INDEX "recruiter_invite_email_idx" ON "production"."recruiter_invite" USING btree ("email","status");--> statement-breakpoint
CREATE UNIQUE INDEX "recruiter_suggestion_pending_idx" ON "production"."recruiter_suggestion" USING btree ("candidate_id","job_id") WHERE "production"."recruiter_suggestion"."status" = 'pending';--> statement-breakpoint
CREATE UNIQUE INDEX "recruiter_suggestion_by_idx" ON "production"."recruiter_suggestion_by" USING btree ("suggestion_id","recruiter_user_id");--> statement-breakpoint
CREATE INDEX "recruiter_suggestion_by_recruiter_idx" ON "production"."recruiter_suggestion_by" USING btree ("recruiter_user_id","created_at");--> statement-breakpoint
-- Etapa de dados escrita à mão (#465, ADR-011): cada vínculo de
-- recruiter_candidate vira uma concessão ativa, sem fim, com o e-mail atual da
-- conta e o autor e a data preservados, mais um evento grant_created do sistema.
-- recruiter_candidate fica congelada (sem leitura nem escrita) e NÃO é removida.
INSERT INTO "production"."recruiter_grant" ("candidate_id", "recruiter_user_id", "recruiter_email", "status", "created_by", "created_at")
SELECT rc."candidate_id", rc."recruiter_user_id", lower(btrim(u."email")), 'active', rc."created_by", rc."created_at"
FROM "production"."recruiter_candidate" rc
JOIN "production"."auth_user" u ON u."id" = rc."recruiter_user_id"
ORDER BY rc."id";--> statement-breakpoint
INSERT INTO "production"."recruiter_access_event" ("candidate_id", "grant_id", "recruiter_email", "kind", "actor", "at")
SELECT g."candidate_id", g."id", g."recruiter_email", 'grant_created', 'system', g."created_at"
FROM "production"."recruiter_grant" g
WHERE NOT EXISTS (
  SELECT 1 FROM "production"."recruiter_access_event" e WHERE e."grant_id" = g."id"
)
ORDER BY g."id";