import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Executable architecture rules.
 *
 * Every assertion here is already true today — that is deliberate. A fitness
 * test that starts red is a wish; one that starts green is a wall. These exist
 * so the ADR 0007 migration cannot silently regress while two conventions live
 * side by side, which the panel named as its own biggest risk.
 */

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (full.endsWith(".ts") || full.endsWith(".tsx")) out.push(full);
  }
  return out;
}

const SRC = walk("src");
const read = (f: string) => readFileSync(f, "utf8");

describe("erasable TypeScript (ADR 0006)", () => {
  it("uses no enum, namespace, decorator or parameter property", () => {
    const offenders: string[] = [];
    for (const file of SRC) {
      const code = read(file);
      if (/^\s*(export\s+)?enum\s+\w/m.test(code)) offenders.push(`${file}: enum`);
      if (/^\s*(export\s+)?namespace\s+\w/m.test(code)) offenders.push(`${file}: namespace`);
      if (/^\s*@[A-Z]\w*\s*\(/m.test(code)) offenders.push(`${file}: decorator`);
      if (/constructor\s*\([^)]*\b(private|public|readonly|protected)\s+\w/.test(code)) {
        offenders.push(`${file}: parameter property`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("carries explicit .ts extensions on relative imports", () => {
    const offenders: string[] = [];
    for (const file of SRC) {
      for (const m of read(file).matchAll(/from\s+"(\.[^"]+)"/g)) {
        const spec = m[1]!;
        if (!spec.endsWith(".ts") && !spec.endsWith(".tsx") && !spec.endsWith(".json")) {
          offenders.push(`${file}: ${spec}`);
        }
      }
    }
    expect(offenders).toEqual([]);
  });
});

describe("layering", () => {
  it("keeps the skills domain free of infrastructure", () => {
    // The property that makes the extractor testable without a database.
    const domain = SRC.filter((f) => f.includes("contexts/skills/domain"));
    expect(domain.length).toBeGreaterThan(0);

    const offenders: string[] = [];
    for (const file of domain) {
      const code = read(file);
      for (const forbidden of ["drizzle-orm", "db/client", "db/schema", "node:fs"]) {
        if (code.includes(forbidden)) offenders.push(`${file}: ${forbidden}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("keeps src/ free of any dependency on the UI", () => {
    // Careful: `./app/` inside a bounded context is its APPLICATION layer
    // (ADR 0007), not Next's `app/`. Only a path that climbs out of src/ or
    // uses the `@/app` alias is actually reaching into the UI.
    const offenders = SRC.filter(
      (f) => /from\s+"(?:\.\.\/)+app\//.test(read(f)) || /from\s+"(?:@\/app\/|next\/)/.test(read(f)),
    );
    expect(offenders).toEqual([]);
  });
});

describe("write-path invariants (ADR 0005)", () => {
  it("routes every application status change through setApplicationStatus", () => {
    // Ingestion must never write the funnel. If a second write path appears,
    // this fails before anyone notices decisions being overwritten.
    const offenders: string[] = [];
    const ingestion = SRC.filter(
      (f) =>
        f.includes("src/core/ingest") ||
        f.includes("src/core/sources") ||
        f.includes("src/core/mail"),
    );
    for (const file of ingestion) {
      const code = read(file);
      if (/\.(insert|update)\(\s*application\s*\)/.test(code)) {
        offenders.push(`${file}: writes application directly`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("closes jobs instead of deleting them", () => {
    const run = read("src/core/ingest/run.ts");
    expect(run).toContain("closedAt");
    // The only delete in the sync path is pruneClosed, and it is guarded.
    const prune = run.slice(run.indexOf("pruneClosed"));
    expect(prune).toContain("not in (select job_id from application)");
  });
});

describe("scoring purity (ADR 0004)", () => {
  it("never reaches the network", () => {
    for (const file of SRC.filter((f) => f.includes("src/core/scoring"))) {
      const code = read(file);
      expect(code, file).not.toContain("fetch(");
      expect(code, file).not.toContain("getJson");
    }
  });

  it("keeps SCORER_VERSION declared where the weights live", () => {
    const score = read("src/core/scoring/score.ts");
    expect(score).toMatch(/SCORER_VERSION\s*=\s*"\d+\.\d+\.\d+"/);
  });
});

describe("floating layers", () => {
  // Base UI confines a popup to its anchor's clipping ancestors by default.
  // Every `Card` sets `overflow-hidden`, and filters, selects and buttons all
  // live inside cards — so the default clipped tooltips in half. These files
  // are generated by the shadcn CLI, and regenerating one would silently drop
  // the fix; this fails loudly instead.
  const POPUPS = ["components/ui/tooltip.tsx", "components/ui/select.tsx"];

  it("gives every Positioner a collision boundary that is not its clipping ancestor", () => {
    const offenders: string[] = [];
    for (const file of POPUPS) {
      const code = read(file);
      if (!code.includes("Positioner")) continue;
      if (!code.includes("collisionBoundary")) offenders.push(`${file}: no collisionBoundary`);
      if (!code.includes("useBodyBoundary")) offenders.push(`${file}: not using useBodyBoundary`);
    }
    expect(offenders).toEqual([]);
  });

  it("resolves the boundary without waiting for an effect", () => {
    // An effect-resolved boundary positions the first frame against the wrong
    // box and visibly jumps.
    const hook = read("lib/popup-boundary.ts");
    expect(hook).toContain("useState");
    expect(hook).not.toContain("useEffect");
    // Must stay safe to import from a file that also renders on the server.
    expect(hook).toContain('typeof document === "undefined"');
  });
});

describe("pluggability (rule 4)", () => {
  // The system exists to receive modules: sources, queues, LLM providers. Each
  // is a port with adapters, and the value only survives if the boundary does.
  it("keeps every port free of a concrete implementation", () => {
    const ports = SRC.filter((f) => f.endsWith("ports.ts") || f.endsWith("llm/port.ts"));
    expect(ports.length).toBeGreaterThan(0);

    const offenders: string[] = [];
    for (const file of ports) {
      const code = read(file);
      for (const forbidden of ["drizzle-orm", "getDb", "node:fs"]) {
        if (code.includes(forbidden)) offenders.push(`${file}: ${forbidden}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("never hard-codes an LLM provider outside its adapter file", () => {
    // A direct call to api.anthropic.com anywhere else would defeat BYOK: the
    // user could no longer choose, and the key would spread.
    const offenders = SRC.filter(
      (f) => !f.endsWith("llm/providers.ts") && /api\.(anthropic|openai)\.com/.test(read(f)),
    );
    expect(offenders).toEqual([]);
  });

  it("handles the API key only where authentication happens", () => {
    // `providers.ts` must touch the key — it is what signs the request. Nowhere
    // else has any reason to, and a key that spreads is a key that leaks.
    const allowed = "src/core/llm/providers.ts";
    const offenders = SRC.filter(
      (f) => f !== allowed && /\bapiKey\b/.test(read(f)) && !/apiKeyEnv/.test(read(f)),
    );
    expect(offenders).toEqual([]);
  });

  it("never writes a key to the database", () => {
    // The registry stores the NAME of the environment variable. A database file
    // gets copied, backed up and opened by other processes; a key inside it
    // travels with all of that.
    const schema = read("src/core/db/schema.ts");
    expect(schema).toContain("apiKeyEnv");
    expect(schema).not.toMatch(/apiKey:\s*text\("api_key"/);
  });

  it("never prints a key", () => {
    const offenders = SRC.filter((f) => /console\.(log|error)\([^)]*\bapiKey\b/.test(read(f)));
    expect(offenders).toEqual([]);
  });
});

describe("authorisation (AUTH-01)", () => {
  const APP = walk("app").filter((f) => f.endsWith("actions.ts"));

  /**
   * The one action that may not be guarded, and why.
   *
   * Sign-in is where a session begins, so requiring one would be circular. It
   * is the only unauthenticated write in the system, which is why the rate
   * limit lives underneath it. Listed here explicitly so the exception is a
   * decision on the record rather than an omission nobody noticed.
   */
  const UNGUARDED_BY_DESIGN = new Set(["passwordLoginAction"]);

  it("guards every Server Action", () => {
    // A Server Action is a public HTTP endpoint. One that forgets the guard is
    // reachable by anyone who can reach the server, and the omission is
    // invisible in review because the file looks like ordinary code.
    expect(APP.length).toBeGreaterThan(0);
    const offenders: string[] = [];

    for (const file of APP) {
      const code = read(file);
      if (!code.includes('"use server"')) continue;

      for (const match of code.matchAll(/export async function (\w+)\s*\([^)]*\)\s*\{/g)) {
        const name = match[1]!;
        if (UNGUARDED_BY_DESIGN.has(name)) continue;
        const body = code.slice(match.index, code.indexOf("\n}", match.index));
        if (!/await guard(OwnCandidate)?\(/.test(body)) {
          offenders.push(`${file}: ${name}`);
        }
      }
    }
    expect(offenders).toEqual([]);
  });

  it("rate-limits the one action that cannot be guarded", () => {
    // Sign-in is unauthenticated by necessity, so the protection has to be a
    // limit rather than a permission.
    const login = read("src/contexts/auth/infra/password-login.ts");
    expect(login).toContain("MAX_ATTEMPTS");
    expect(login).toContain("recentFailures");
  });

  it("answers identically for a wrong password and a missing account", () => {
    // Anything else turns the login form into an account-enumeration oracle.
    const login = read("src/contexts/auth/infra/password-login.ts");
    expect(login).toContain("decoy");
    const action = read("app/login/actions.ts");
    expect(action).not.toMatch(/conta (não existe|inexistente)/i);
  });

  it("hashes passwords with a memory-hard KDF, never a plain digest", () => {
    const pw = read("src/contexts/auth/domain/password.ts");
    expect(pw).toContain("scrypt");
    expect(pw).toContain("timingSafeEqual");
    expect(pw).not.toMatch(/createHash\(["']sha256["']\)/);
  });

  it("never lets an action take a candidate id from its own input", () => {
    // The classic multi-tenant leak: the UI filters correctly, and a hand-made
    // POST with someone else's id walks straight through. Scope must come from
    // the session, which is why `guardOwnCandidate` takes no id at all.
    const offenders: string[] = [];
    for (const file of APP) {
      const code = read(file);
      if (/formData\.get\(\s*["']candidateId["']/.test(code)) offenders.push(file);
    }
    expect(offenders).toEqual([]);
  });

  it("redeems the magic link in a Route Handler, never in a page", () => {
    // Next only allows cookies to be MODIFIED in a Server Action or Route
    // Handler. Doing it while rendering /login threw at runtime — the framework
    // enforcing a boundary that is correct, since rendering should be
    // replayable and starting a session is not.
    const page = read("app/login/page.tsx");
    expect(page).not.toMatch(/cookies\(\)/);
    expect(page).not.toContain("finishLogin");

    const handler = read("app/login/callback/route.ts");
    expect(handler).toContain("finishLogin");
    expect(handler).toContain("cookies()");
  });

  it("sets the session cookie httpOnly and never exposes it to script", () => {
    const handler = read("app/login/callback/route.ts");
    expect(handler).toContain("httpOnly: true");
    expect(handler).toContain("sameSite:");
  });

  it("revokes server-side on logout, not just clears the cookie", () => {
    // Cookie que o cliente apaga continua válido para quem o copiou.
    // Server Action, não Route Handler: a CSP declara `form-action 'self'` e
    // bloqueava o POST de formulário para outra rota — o logout não acontecia,
    // com o erro apenas no console.
    const logout = read("app/logout-action.ts");
    expect(logout).toContain("endSession");
    expect(logout).toContain('"use server"');
  });

  it("protege por omissão", () => {
    // O padrão era `single-user`, que sintetizava sessão e deixava currículo,
    // funil e o export CSV inteiro acessíveis a qualquer requisição. Agora o
    // modo aberto tem de ser pedido.
    const session = read("src/contexts/auth/app/session.ts");
    expect(session).toContain('env.JHO_AUTH_MODE === "open"');
    const middleware = readFileSync("middleware.ts", "utf8");
    expect(middleware).toContain('process.env.JHO_AUTH_MODE === "open"');
  });

  it("keeps the permission decision in one pure function", () => {
    // Authorisation bugs come from a check that exists in four places and
    // disagrees with itself in one.
    const policy = read("src/contexts/auth/domain/policy.ts");
    for (const forbidden of ["drizzle-orm", "getDb", "cookies", "next/"]) {
      expect(policy, forbidden).not.toContain(forbidden);
    }
    // And it must never fall through to permitted.
    expect(policy).not.toMatch(/default:\s*\n?\s*return ALLOW/);
  });
});
