import { sql } from "drizzle-orm";
import { afterEach, beforeEach, expect, it } from "vitest";
import { connectDatabase, type DB } from "../src/core/db/client.ts";
import { candidate } from "../src/core/db/schema.ts";
import { useTestDb, releaseTestDb } from "./support/db.ts";
import { provisionRuntimeLogin } from "./support/runtime-login.ts";

let db: DB;
beforeEach(async () => { db = await useTestDb(); });
afterEach(async () => { await releaseTestDb(); });

it("uses a real runtime login that cannot switch back to the database owner", async () => {
  const login = await provisionRuntimeLogin(process.env.DATABASE_URL!);
  const runtime = connectDatabase(login.url);
  try {
    const [row] = await runtime.db.insert(candidate).values({ slug: "login", name: "Login" }).returning();
    expect(row!.id).toBeGreaterThan(0);
    await expect(runtime.db.execute(sql`SET ROLE postgres`)).rejects.toMatchObject({ cause: { code: "42501" } });
    await expect(runtime.db.execute(sql`CREATE TABLE production.forbidden (id integer)`)).rejects.toMatchObject({ cause: { code: "42501" } });
  } finally { await runtime.client.end(); await login.drop(); }
});

it("allows runtime CRUD and identity allocation with no ownership or administrative attributes", async () => {
  await db.transaction(async (tx) => {
    await tx.execute(sql`SET LOCAL ROLE master_jobs_runtime`);
    const [created] = await tx.insert(candidate).values({ slug: "runtime", name: "Runtime" }).returning();
    expect(created!.id).toBeGreaterThan(0);
    expect(await tx.select().from(candidate)).toHaveLength(1);
    await tx.update(candidate).set({ name: "Changed" });
    expect((await tx.select().from(candidate))[0]!.name).toBe("Changed");
    await tx.delete(candidate);
    expect(await tx.select().from(candidate)).toHaveLength(0);
    const [role] = await tx.execute(sql`SELECT rolsuper, rolcreatedb, rolcreaterole, rolcanlogin, rolbypassrls FROM pg_roles WHERE rolname = current_user`);
    expect(Object.values(role!)).toEqual([false, false, false, false, false]);
  });
});

it("refuses DDL, truncation and access to migration history", async () => {
  for (const query of [
    sql`CREATE TABLE production.forbidden (id integer)`,
    sql`ALTER TABLE production.candidate ADD COLUMN forbidden text`,
    sql`TRUNCATE production.candidate CASCADE`,
    sql`SELECT * FROM drizzle.__drizzle_migrations`,
    sql`CREATE ROLE forbidden_runtime_role`,
  ]) {
    await expect(db.transaction(async (tx) => {
      await tx.execute(sql`SET LOCAL ROLE master_jobs_runtime`);
      await tx.execute(query);
    })).rejects.toMatchObject({ cause: { code: "42501" } });
  }
});

it("grants future tables to runtime without granting schema access to PUBLIC", async () => {
  await db.execute(sql`CREATE TABLE production.future_access_probe (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value text)`);
  await db.transaction(async (tx) => {
    await tx.execute(sql`SET LOCAL ROLE master_jobs_runtime`);
    await tx.execute(sql`INSERT INTO production.future_access_probe(value) VALUES ('allowed')`);
    expect(await tx.execute(sql`SELECT value FROM production.future_access_probe`)).toEqual([{ value: "allowed" }]);
  });
  const [schema] = await db.execute(sql`SELECT count(*)::integer AS grants FROM pg_namespace n,
    LATERAL aclexplode(n.nspacl) acl WHERE n.nspname = 'production' AND acl.grantee = 0`);
  expect(schema!.grants).toBe(0);
});

it("blocks all Data API roles, including a role with BYPASSRLS", async () => {
  for (const principal of ["anon", "authenticated", "service_role"]) {
    await expect(db.transaction(async (tx) => {
      await tx.execute(sql`SET LOCAL ROLE ${sql.identifier(principal)}`);
      await tx.select().from(candidate);
    })).rejects.toMatchObject({ cause: { code: "42501" } });
  }
});
