/**
 * Applies the SQL migrations generated by drizzle-kit.
 *
 * Kept as code (rather than only `drizzle-kit migrate`) so the CLI, the tests
 * and a future Vercel deploy hook all bootstrap the database the same way.
 */
import { migrate } from "drizzle-orm/libsql/migrator";
import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import { getDb } from "./client.ts";

export async function runMigrations(folder = "./drizzle"): Promise<void> {
  const url = process.env.TURSO_DATABASE_URL ?? "file:./data/jobs.db";
  // A local file database needs its directory to exist before libSQL opens it.
  if (url.startsWith("file:")) {
    const path = url.slice("file:".length);
    await mkdir(dirname(path), { recursive: true });
  }
  await migrate(getDb(), { migrationsFolder: folder });
}
