/**
 * Curated global skill catalogue.
 *
 * Aliases come from this corpus or the candidate's CV. Ambiguous short forms
 * are omitted deliberately; the canonical matcher still recognizes an exact
 * display name with safe word boundaries.
 */
import type { SkillDefinition } from "./types.ts";

export const SKILL_CATALOG = [
  { slug: "typescript", name: "TypeScript", category: "language", aliases: ["typescript"] },
  { slug: "javascript", name: "JavaScript", category: "language", aliases: ["javascript", "ecmascript"] },
  { slug: "python", name: "Python", category: "language", aliases: ["python"] },
  { slug: "go", name: "Go", category: "language", aliases: ["golang"] },
  { slug: "rust", name: "Rust", category: "language", aliases: ["rust"] },
  { slug: "php", name: "PHP", category: "language", aliases: ["php"] },
  { slug: "kotlin", name: "Kotlin", category: "language", aliases: ["kotlin"] },
  { slug: "swift", name: "Swift", category: "language", aliases: ["swift"] },
  { slug: "java", name: "Java", category: "language", aliases: ["java"] },
  { slug: "csharp", name: "C#", category: "language", aliases: ["c#", "csharp"] },
  { slug: "ruby", name: "Ruby", category: "language", aliases: ["ruby", "ruby on rails"] },
  { slug: "elixir", name: "Elixir", category: "language", aliases: ["elixir"] },

  { slug: "react", name: "React", category: "framework", aliases: ["react", "react.js", "reactjs"] },
  { slug: "nextjs", name: "Next.js", category: "framework", aliases: ["next.js", "nextjs"] },
  { slug: "nodejs", name: "Node.js", category: "framework", aliases: ["node.js", "nodejs"] },
  { slug: "vue", name: "Vue.js", category: "framework", aliases: ["vue", "vue.js", "vuejs"] },
  { slug: "angular", name: "Angular", category: "framework", aliases: ["angular", "angularjs"] },
  { slug: "fastapi", name: "FastAPI", category: "framework", aliases: ["fastapi"] },
  { slug: "django", name: "Django", category: "framework", aliases: ["django"] },
  { slug: "flask", name: "Flask", category: "framework", aliases: ["flask"] },
  { slug: "laravel", name: "Laravel", category: "framework", aliases: ["laravel", "jetstream", "nova"] },
  { slug: "nestjs", name: "NestJS", category: "framework", aliases: ["nest.js", "nestjs"] },
  { slug: "express", name: "Express", category: "framework", aliases: ["express.js", "expressjs"] },
  { slug: "codeigniter", name: "CodeIgniter", category: "framework", aliases: ["codeigniter"] },
  { slug: "react-native", name: "React Native", category: "framework", aliases: ["react native"] },
  { slug: "ionic", name: "Ionic", category: "framework", aliases: ["ionic"] },
  { slug: "electron", name: "Electron", category: "framework", aliases: ["electron"] },
  { slug: "tailwind", name: "Tailwind CSS", category: "framework", aliases: ["tailwind", "tailwindcss"] },
  { slug: "socketio", name: "Socket.IO", category: "framework", aliases: ["socket.io", "socketio", "websockets"] },

  { slug: "llm", name: "LLM", category: "ai", aliases: ["llm", "llms", "large language model"] },
  { slug: "rag", name: "RAG", category: "ai", aliases: ["rag", "retrieval augmented generation", "retrieval-augmented"] },
  { slug: "agentic", name: "Agentic AI", category: "ai", aliases: ["agentic", "ai agents", "agent orchestration"] },
  { slug: "multi-agent", name: "Multi-agent systems", category: "ai", aliases: ["multi-agent", "multi agent"] },
  { slug: "langchain", name: "LangChain", category: "ai", aliases: ["langchain"] },
  { slug: "langgraph", name: "LangGraph", category: "ai", aliases: ["langgraph"] },
  { slug: "langsmith", name: "LangSmith", category: "ai", aliases: ["langsmith"] },
  { slug: "evals", name: "Evals", category: "ai", aliases: ["evals", "golden dataset", "golden set", "evaluation framework"] },
  { slug: "guardrails", name: "Guardrails", category: "ai", aliases: ["guardrails", "guardrail"] },
  { slug: "llmops", name: "LLMOps", category: "ai", aliases: ["llmops"] },
  { slug: "prompt-engineering", name: "Prompt engineering", category: "ai", aliases: ["prompt engineering", "context engineering"] },
  { slug: "embeddings", name: "Embeddings", category: "ai", aliases: ["embeddings", "embedding model"] },
  { slug: "vector-db", name: "Vector databases", category: "ai", aliases: ["vector database", "vector db", "pinecone", "pgvector", "weaviate", "qdrant"] },
  { slug: "reranking", name: "Reranking", category: "ai", aliases: ["reranking", "re-ranking", "reranker"] },
  { slug: "fine-tuning", name: "Fine-tuning", category: "ai", aliases: ["fine-tuning", "fine tuning", "finetuning"] },
  { slug: "tool-calling", name: "Tool calling", category: "ai", aliases: ["tool calling", "function calling", "tool use"] },
  { slug: "pytorch", name: "PyTorch", category: "ai", aliases: ["pytorch"] },
  { slug: "tensorflow", name: "TensorFlow", category: "ai", aliases: ["tensorflow", "keras"] },
  { slug: "openai", name: "OpenAI", category: "ai", aliases: ["openai"] },
  { slug: "anthropic", name: "Anthropic", category: "ai", aliases: ["anthropic"] },
  { slug: "huggingface", name: "Hugging Face", category: "ai", aliases: ["hugging face", "huggingface"] },
  { slug: "mlflow", name: "MLflow", category: "ai", aliases: ["mlflow"] },
  { slug: "nlp", name: "NLP", category: "ai", aliases: ["nlp", "natural language processing", "spacy", "nltk", "bert", "transformers"] },

  { slug: "aws", name: "AWS", category: "cloud", aliases: ["aws", "amazon web services", "aws lambda"] },
  { slug: "gcp", name: "GCP", category: "cloud", aliases: ["gcp", "google cloud"] },
  { slug: "azure", name: "Azure", category: "cloud", aliases: ["azure"] },
  { slug: "kubernetes", name: "Kubernetes", category: "cloud", aliases: ["kubernetes", "k8s"] },
  { slug: "docker", name: "Docker", category: "cloud", aliases: ["docker"] },
  { slug: "terraform", name: "Terraform", category: "cloud", aliases: ["terraform"] },
  { slug: "ansible", name: "Ansible", category: "cloud", aliases: ["ansible"] },
  { slug: "serverless", name: "Serverless", category: "cloud", aliases: ["serverless"] },

  { slug: "postgres", name: "PostgreSQL", category: "data", aliases: ["postgres", "postgresql"] },
  { slug: "mysql", name: "MySQL", category: "data", aliases: ["mysql", "mariadb"] },
  { slug: "mongodb", name: "MongoDB", category: "data", aliases: ["mongodb"] },
  { slug: "redis", name: "Redis", category: "data", aliases: ["redis"] },
  { slug: "sqlserver", name: "SQL Server", category: "data", aliases: ["sql server"] },
  { slug: "couchbase", name: "Couchbase", category: "data", aliases: ["couchbase"] },
  { slug: "dynamodb", name: "DynamoDB", category: "data", aliases: ["dynamodb"] },
  { slug: "sqlite", name: "SQLite", category: "data", aliases: ["sqlite", "libsql"] },
  { slug: "kafka", name: "Kafka", category: "data", aliases: ["kafka"] },
  { slug: "etl", name: "ETL", category: "data", aliases: ["etl", "data pipeline", "data pipelines"] },
  { slug: "bi", name: "Business Intelligence", category: "data", aliases: ["business intelligence"] },
  { slug: "data-governance", name: "Data governance", category: "data", aliases: ["data governance", "data quality"] },

  { slug: "architecture", name: "Software architecture", category: "practice", aliases: ["software architecture", "solution architecture"] },
  { slug: "distributed-systems", name: "Distributed systems", category: "practice", aliases: ["distributed systems", "distributed system"] },
  { slug: "system-design", name: "System design", category: "practice", aliases: ["system design"] },
  { slug: "microservices", name: "Microservices", category: "practice", aliases: ["microservices", "microservice"] },
  { slug: "event-driven", name: "Event-driven architecture", category: "practice", aliases: ["event-driven", "event driven", "event sourcing"] },
  { slug: "multi-tenant", name: "Multi-tenancy", category: "practice", aliases: ["multi-tenant", "multitenant", "multi-tenancy"] },
  { slug: "observability", name: "Observability", category: "practice", aliases: ["observability", "datadog", "opentelemetry", "rollbar"] },
  { slug: "cicd", name: "CI/CD", category: "practice", aliases: ["ci/cd", "cicd", "continuous integration", "github actions", "jenkins"] },
  { slug: "tdd", name: "TDD", category: "practice", aliases: ["tdd", "test-driven", "test driven"] },
  { slug: "ddd", name: "DDD", category: "practice", aliases: ["domain-driven", "domain driven"] },
  { slug: "sdd", name: "Spec-Driven Development", category: "practice", aliases: ["spec-driven development"] },
  { slug: "legacy-modernization", name: "Legacy modernization", category: "practice", aliases: ["legacy modernization", "modernization", "modernizing"] },
  { slug: "security", name: "Security", category: "practice", aliases: ["owasp", "devsecops", "threat modeling", "sonarqube", "snyk"] },
  { slug: "performance", name: "Performance engineering", category: "practice", aliases: ["performance optimization", "cost optimization"] },
  { slug: "api-design", name: "API design", category: "practice", aliases: ["api design", "rest api", "graphql", "grpc"] },
  { slug: "testing", name: "Test automation", category: "practice", aliases: ["playwright", "cypress", "phpunit", "vitest", "test automation", "qa automation"] },
  { slug: "agile", name: "Agile", category: "practice", aliases: ["agile", "scrum", "kanban"] },

  { slug: "fintech", name: "Fintech", category: "domain", aliases: ["fintech", "financial services"] },
  { slug: "healthcare", name: "Healthcare", category: "domain", aliases: ["healthcare", "healthtech", "clinics"] },
  { slug: "ecommerce", name: "E-commerce", category: "domain", aliases: ["e-commerce", "ecommerce", "magento"] },
  { slug: "erp", name: "ERP", category: "domain", aliases: ["erp"] },
  { slug: "gaming", name: "Gaming", category: "domain", aliases: ["casino games", "game engineer"] },
  { slug: "saas", name: "SaaS", category: "domain", aliases: ["saas"] },
  { slug: "pos", name: "POS", category: "domain", aliases: ["point of sale"] },

  { slug: "tech-leadership", name: "Technical leadership", category: "soft", aliases: ["technical leadership", "tech lead", "engineering lead"] },
  { slug: "mentoring", name: "Mentoring", category: "soft", aliases: ["mentoring", "mentor", "coaching"] },
  { slug: "stakeholder", name: "Stakeholder management", category: "soft", aliases: ["stakeholder", "stakeholders", "cross-functional"] },
  { slug: "english", name: "English (fluent)", category: "soft", aliases: ["english"] },
] as const satisfies readonly SkillDefinition[];
