/**
 * The action plan from section 14 of the positioning audit
 * (Relatorio-Posicionamento-Andreus-Timm-2026-07-27.md), as executable rows.
 *
 * Kept as data rather than prose so progress is queryable and the agent can
 * report on it. Seeding is idempotent: re-running never resets a task you
 * already completed.
 */
import type { NewPositioningTask } from "../db/schema.ts";

export const POSITIONING_PLAN: NewPositioningTask[] = [
  /* ---------------------------- primeiras 24h ---------------------------- */
  {
    id: "PT-0001",
    horizon: "24h",
    priority: "P0",
    effort: "15 min",
    title: "Alinhar os cargos do Open to Work",
    why: "Os cargos configurados (JavaScript/Python/Backend/Full Stack Developer) direcionam o algoritmo e recrutadores para vagas abaixo do alvo. É o maior vazamento de oportunidades identificado.",
    how: "Trocar por Architect / Staff / Principal / AI Engineering Lead; manter remoto e contrato.",
    expected: "Mais impressões qualificadas e recomendações de vaga no nível certo.",
    sourceRef: "§14 Primeiras 24 horas · §1.2 · §16",
  },
  {
    id: "PT-0002",
    horizon: "24h",
    priority: "P0",
    effort: "5 min",
    title: "Trocar a headline",
    why: "A headline começa forte e perde força em termos ambíguos (Loop Engineering, Context Architect, Harness Engineering, TPM, HIC) que reduzem correspondência com termos padronizados.",
    how: "Usar a headline principal pronta na §12.1 do relatório.",
    expected: "Proposta de valor clara em segundos no primeiro scan.",
    sourceRef: "§14 Primeiras 24 horas · §3.2 · §12.1",
  },
  {
    id: "PT-0003",
    horizon: "24h",
    priority: "P0",
    effort: "20 min",
    title: "Reordenar as 5 competências principais",
    why: "As competências prioritárias hoje não sinalizam nível Staff/Architect.",
    how: "Ordem: Software Architecture, AI, Distributed Systems, Technical Leadership, SaaS.",
    expected: "Coerência entre perfil e busca por recrutador.",
    sourceRef: "§14 Primeiras 24 horas · §3.7",
  },
  {
    id: "PT-0004",
    horizon: "24h",
    priority: "P0",
    effort: "5 min",
    title: "Atualizar a bio do GitHub",
    why: "A bio atual mistura generalismo e não conversa com o posicionamento do LinkedIn.",
    how: "Usar a bio curta pronta na §12.5.",
    expected: "Coerência imediata entre perfis.",
    sourceRef: "§14 Primeiras 24 horas · §12.5",
  },
  {
    id: "PT-0005",
    horizon: "24h",
    priority: "P2",
    effort: "5 min",
    title: "Limpar informações de contato",
    why: "Hangouts e data de aniversário são ruído e exposição desnecessária.",
    how: "Remover ambos; manter e-mail.",
    expected: "Perfil mais limpo e profissional.",
    sourceRef: "§14 Primeiras 24 horas",
  },
  {
    id: "PT-0006",
    horizon: "24h",
    priority: "P1",
    effort: "10 min",
    title: "Registrar a baseline de métricas",
    why: "Sem baseline não há como saber se as mudanças funcionaram.",
    how: "Registrar em metric_snapshot: SSI 59, 72 ocorrências em busca, 1.362 exibições, 5,3% vindas de pesquisa, 97 visualizações por recrutadores/ano.",
    expected: "Comparação possível em 30/60/90 dias.",
    sourceRef: "§14 Primeiras 24 horas · §2.1",
  },

  /* ---------------------------- primeira semana --------------------------- */
  {
    id: "PT-0007",
    horizon: "week",
    priority: "P0",
    effort: "90 min",
    title: "Publicar o novo About em inglês e português",
    why: "Converter visitas em interesse real; hoje o About é longo e sem foco.",
    how: "Revisar os textos prontos das §12.3 e §12.4, validar C2, datas e nomes, publicar em cada idioma.",
    expected: "Mais clareza e keywords naturais.",
    sourceRef: "§14 Primeira semana · §12.3 · §12.4",
  },
  {
    id: "PT-0008",
    horizon: "week",
    priority: "P0",
    effort: "2 h",
    title: "Reescrever a experiência na Master Timm",
    why: "Quatro clientes e papéis relevantes estão comprimidos numa única experiência, escondendo nomes, cargos e datas dos filtros do LinkedIn.",
    how: "Usar subheadings por cliente, ou contratos separados se permitido. Modelo pronto na §12.8.",
    expected: "Melhor leitura e indexação.",
    sourceRef: "§14 Primeira semana · §3.5 · §12.8",
  },
  {
    id: "PT-0009",
    horizon: "week",
    priority: "P0",
    effort: "30 min",
    title: "Resolver inconsistências entre fontes",
    why: "Datas e idiomas divergem entre LinkedIn, GitHub e currículo, o que gera dúvida.",
    how: "Confirmar 2023 vs jan/2024 e padronizar idiomas.",
    expected: "Confiança do leitor.",
    sourceRef: "§14 Primeira semana · §5",
  },
  {
    id: "PT-0010",
    horizon: "week",
    priority: "P1",
    effort: "2 h",
    title: "Corrigir metadata dos dois repositórios fixados",
    why: "Ambos estão sem descrição, topics e releases; um tem o nome grafado incorretamente.",
    how: "Corrigir nome, descrição, topics e LICENSE.",
    expected: "Vitrine técnica mais profissional.",
    sourceRef: "§14 Primeira semana · §4.1",
  },
  {
    id: "PT-0011",
    horizon: "week",
    priority: "P1",
    effort: "45 min",
    title: "Publicar o primeiro post",
    why: "Reativar autoridade; o pilar de engajamento é o mais fraco do SSI (8,10/25).",
    how: "Usar o Post 1 ou 2 prontos da §13.6; responder todos os comentários.",
    expected: "Mais alcance qualificado.",
    sourceRef: "§14 Primeira semana · §13.6",
  },
  {
    id: "PT-0012",
    horizon: "week",
    priority: "P1",
    effort: "1 h",
    title: "Mapear as 30 contas-alvo",
    why: "A descoberta hoje vem da rede, não de busca intencional.",
    how: "10 recrutadores, 10 líderes de AI/platform, 10 pares Staff/Principal. Registrar em target_account.",
    expected: "Feed e rede mais relevantes.",
    sourceRef: "§14 Primeira semana · §2.2",
  },

  /* ------------------------------ 30 dias -------------------------------- */
  {
    id: "PT-0013",
    horizon: "30d",
    priority: "P0",
    effort: "12–20 h",
    title: "Publicar o case study do Zorbit",
    why: "É o melhor ativo técnico e está invisível — privado e sem estudo de caso público.",
    how: "Sanitizar, diagramar, explicar decisões e autoria. Corrigir alertas de segurança antes.",
    expected: "Prova forte para Architect/Staff.",
    sourceRef: "§14 Primeiros 30 dias · §4.2",
  },
  {
    id: "PT-0014",
    horizon: "30d",
    priority: "P0",
    effort: "10–16 h",
    title: "Publicar o case study do Contas Casal",
    why: "Demonstra produto real com IA aplicada em produção.",
    how: "Sem PII nem código privado; focar arquitetura, testes, observabilidade e IA.",
    expected: "Prova de SaaS e production AI.",
    sourceRef: "§14 Primeiros 30 dias · §4.2",
  },
  {
    id: "PT-0015",
    horizon: "30d",
    priority: "P0",
    effort: "8–16 h",
    title: "Corrigir o chatbot-openai-interview e prepará-lo para pin",
    why: "Falta código público executável como prova hands-on.",
    how: "Resolver os 20 alertas, adicionar demo, screenshots, release e LICENSE.",
    expected: "Prova hands-on segura e verificável.",
    sourceRef: "§14 Primeiros 30 dias · §4.2",
  },
  {
    id: "PT-0016",
    horizon: "30d",
    priority: "P1",
    effort: "1 h",
    title: "Reorganizar a seção Featured",
    why: "Hoje tem apenas um link; a conversão está sendo perdida.",
    how: "Cases primeiro, guia e GitHub depois. Texto pronto na §12.7.",
    expected: "Mais cliques em prova relevante.",
    sourceRef: "§14 Primeiros 30 dias · §12.7",
  },
  {
    id: "PT-0017",
    horizon: "30d",
    priority: "P1",
    effort: "1 h + follow-up",
    title: "Solicitar duas recomendações",
    why: "Prova social é a principal lacuna não técnica — só 2 recomendações, uma de 2012.",
    how: "Um cliente ou líder e um par. Pedido contextual, citando o projeto específico.",
    expected: "Validação atual de arquitetura e IA.",
    sourceRef: "§14 Primeiros 30 dias · §3.8",
  },
  {
    id: "PT-0018",
    horizon: "30d",
    priority: "P1",
    effort: "8–10 h/mês",
    title: "Publicar 4 posts e 40 comentários substantivos",
    why: "Autoridade se constrói por cadência, não por picos.",
    how: "1 post/semana + 2 comentários/dia útil nas contas-alvo. Registrar temas e respostas.",
    expected: "Mais exposição via posts e pesquisa.",
    sourceRef: "§14 Primeiros 30 dias · §13.3",
  },
  {
    id: "PT-0019",
    horizon: "30d",
    priority: "P2",
    effort: "3 h",
    title: "Arquivar 10–20 repositórios de baixo sinal",
    why: "Forks, cursos e exercícios antigos poluem a curadoria do GitHub.",
    how: "Revisar um por um. Não excluir nada com trabalho relevante.",
    expected: "GitHub mais legível em 60 segundos.",
    sourceRef: "§14 Primeiros 30 dias · §4.3",
  },

  /* ------------------------------ 60 dias -------------------------------- */
  {
    id: "PT-0020",
    horizon: "60d",
    priority: "P0",
    effort: "4–6 h/semana",
    title: "Candidatar-se de forma segmentada",
    why: "Converter o posicionamento em entrevistas.",
    how: "5–8 vagas por semana, adaptando o topo do CV e o Featured ao cluster da vaga.",
    expected: "Maior taxa de resposta.",
    sourceRef: "§14 Próximos 60 dias",
  },
  {
    id: "PT-0021",
    horizon: "60d",
    priority: "P1",
    effort: "12–20 h",
    title: "Publicar o case de modernização do Mahout",
    why: "Prova modernização e escala — diferencial forte de arquitetura.",
    how: "Branch protection, números atualizados, diagrama, decisões incrementais.",
    expected: "Diferencial competitivo claro.",
    sourceRef: "§14 Próximos 60 dias",
  },
  {
    id: "PT-0022",
    horizon: "60d",
    priority: "P1",
    effort: "12–20 h",
    title: "Transformar o repo de prompts em laboratório",
    why: "Demonstrar método, não lista de dicas.",
    how: "Dataset, evals, benchmark, CI, demo e release.",
    expected: "Evidência concreta de RAG e LLMOps.",
    sourceRef: "§14 Próximos 60 dias",
  },
  {
    id: "PT-0023",
    horizon: "60d",
    priority: "P1",
    effort: "1 h + follow-up",
    title: "Obter mais duas recomendações",
    why: "Completar a matriz de prova social.",
    how: "Um stakeholder de produto e um mentorado.",
    expected: "4 recomendações alinhadas ao posicionamento.",
    sourceRef: "§14 Próximos 60 dias",
  },
  {
    id: "PT-0024",
    horizon: "60d",
    priority: "P1",
    effort: "30 min/semana",
    title: "Medir o funil semanalmente",
    why: "Saber o que funciona em vez de supor.",
    how: "Exibições → buscas → visitas → contatos → entrevistas. Registrar em metric_snapshot.",
    expected: "Ajustes baseados em dados.",
    sourceRef: "§14 Próximos 60 dias · §14 Métricas",
  },
  {
    id: "PT-0025",
    horizon: "60d",
    priority: "P2",
    effort: "12–24 h",
    title: "Criar página de portfólio",
    why: "Reduzir dependência do Linktree e ter funil próprio.",
    how: "Hero + 3 cases + About + contato.",
    expected: "Funil próprio para recrutadores.",
    sourceRef: "§14 Próximos 60 dias",
  },

  /* ------------------------------ 90 dias -------------------------------- */
  {
    id: "PT-0026",
    horizon: "90d",
    priority: "P1",
    effort: "contínuo",
    title: "Completar 12 posts e 3 case studies",
    why: "Autoridade acumulada é o que muda o pilar mais fraco do SSI.",
    how: "Manter a cadência e reaproveitar cases em vídeo e carrossel.",
    expected: "Biblioteca pública coerente.",
    sourceRef: "§14 Próximos 90 dias",
  },
  {
    id: "PT-0027",
    horizon: "90d",
    priority: "P1",
    effort: "1 h",
    title: "Revisar a headline por desempenho",
    why: "Escolher entre Architect e Staff com base em evidência, não em intuição.",
    how: "Comparar períodos de 30 dias, sem mudanças simultâneas.",
    expected: "Escolha baseada em busca e contatos.",
    sourceRef: "§14 Próximos 90 dias",
  },
  {
    id: "PT-0028",
    horizon: "90d",
    priority: "P1",
    effort: "4 h",
    title: "Consolidar o GitHub em 6 pins fortes",
    why: "Facilitar o scan de 60 segundos do recrutador técnico.",
    how: "Sistemas, cases, laboratório e guia. Pinagem sugerida na §4.4.",
    expected: "Vitrine equilibrada.",
    sourceRef: "§14 Próximos 90 dias · §4.4",
  },
  {
    id: "PT-0029",
    horizon: "90d",
    priority: "P1",
    effort: "6–10 h",
    title: "Criar assets de candidatura por cluster",
    why: "Acelerar a resposta e tornar cada aplicação mais específica.",
    how: "One-page case brief e link por cluster de vaga.",
    expected: "Aplicações mais específicas.",
    sourceRef: "§14 Próximos 90 dias",
  },
  {
    id: "PT-0030",
    horizon: "90d",
    priority: "P1",
    effort: "1 h",
    title: "Revisar SSI e métricas contra a baseline",
    why: "Avaliar efeito real sem obsessão pelo número.",
    how: "Comparar com a baseline; observar a qualidade dos recrutadores que chegam.",
    expected: "Nova priorização informada.",
    sourceRef: "§14 Próximos 90 dias",
  },
  {
    id: "PT-0031",
    horizon: "90d",
    priority: "P3",
    effort: "2 h",
    title: "Avaliar lacunas reais de credencial",
    why: "Evitar curso por vaidade.",
    how: "Só buscar certificação se aparecer como bloqueio recorrente em vagas reais — consultável no próprio banco.",
    expected: "Investimento eficiente.",
    sourceRef: "§14 Próximos 90 dias",
  },
];
