import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  changelogFile,
  formatChangelogDiagnostic,
  parseUserChangelog,
  type BuiltUserRelease,
  type ChangelogLocale,
} from "../src/core/changelog.ts";
import { renderChangelogMarkdown } from "./changelog-markdown.ts";

export function compileChangelog(source: string, locale: ChangelogLocale) {
  const parsed = parseUserChangelog(source);
  const releases: BuiltUserRelease[] = parsed.releases.map(({ markdown, ...metadata }) => ({
    ...metadata,
    html: renderChangelogMarkdown(markdown),
  }));
  return {
    releases,
    diagnostics: parsed.issues.map((issue) => formatChangelogDiagnostic(issue, locale)),
  };
}

export async function generateChangelogs(root: string): Promise<void> {
  const changelogs: Record<ChangelogLocale, BuiltUserRelease[]> = { "pt-BR": [], en: [] };
  for (const locale of ["pt-BR", "en"] as const) {
    const source = await readFile(join(root, changelogFile(locale)!), "utf8");
    const compiled = compileChangelog(source, locale);
    for (const diagnostic of compiled.diagnostics) console.warn(diagnostic);
    changelogs[locale] = compiled.releases;
  }
  const directory = join(root, "src/generated");
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, "changelog.ts"), [
    "// Generated by scripts/build-changelog.ts. Server import only; never publish as a static asset.",
    'import type { BuiltUserRelease, ChangelogLocale } from "../core/changelog.ts";',
    `export const changelogs: Record<ChangelogLocale, BuiltUserRelease[]> = ${JSON.stringify(changelogs)};`,
    "",
  ].join("\n"));
}

if (import.meta.main) await generateChangelogs(process.cwd());
